services:
  # 1. Base de Datos (Persistencia de jugadores/equipos)
  # Aplicamos OWASP A01 aislando la DB en una red interna
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistencia física de datos
    networks:
      rugby-net:
        ipv4_address: 172.20.0.10  # IP fija asignada a la DB dentro de Docker

  # 2. Redis (Caché rápida para tokens y sesiones)
  # Optimización máxima: reduce la carga en la DB principal
  cache:
    image: redis:alpine
    networks:
      rugby-net:
        ipv4_address: 172.20.0.20  # IP fija asignada a Redis

  # 3. API (Nuestra lógica en FastAPI con seguridad OWASP)
  api:
    build: ./backend
    ports:
      - "8000:8000"  # Mapeo: Acceso desde tu PC (8000) al contenedor (8000)
    env_file:
      - .env         # Carga variables sensibles (OWASP A05)
    depends_on:
      - db           # La API espera a que la DB esté lista para arrancar
      - cache
    networks:
      rugby-net:
        ipv4_address: 172.20.0.30  # IP FIJA PARA TU API (IP personalizada interna)

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"  # Ahora entrarás por http://10.50.58.19 (puerto 80 por defecto)
      - "443:443" # Pero irá directamente al puerto seguro con certificados TSL
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - api
    networks:
      rugby-net:
        ipv4_address: 172.20.0.40

# Configuración avanzada de Redes (Subnetting)
# Es obligatorio definir 'ipam' para poder usar IPs fijas (ipv4_address)
networks:
  rugby-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16  # Definimos el rango de red privada de la empresa

# Definición de volúmenes para que los datos no se borren al apagar Docker
volumes:
  postgres_data:
